server:
  port: 10888
bootdo:
  uploadPath: c:/var/uploaded_files/
  username: admin
  password: admin123
logging:
  level:
    root: info
    com.bootdo: debug
spring:
  datasource:
    mysql:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.6.70.110:3306/dt_db?useUnicode=true&characterEncoding=utf8
      username: root
      password: f6~R8w3t_K>NjzRg6t
    dorisdb:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.6.70.130:19030/doris_dt
      username: root
      password: Doris@KWe22PeVj74vD
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000
    jedis:
      pool:
        max-idle: 8
        min-idle: 10
        max-active: 100
        max-wait: -1